### ISSUE TITLE
Documentation at docs.typo3.org

### ISSUE THREAD

**Issue by DanielSiepmann** [carsten-walther/image_copyright#1]
You requested documentation rendering at docs.typo3.org.
In order to approve the request, the extension needs to be published at https://extensions.typo3.org/ or https://packagist.org/. Otherwise we can not ensure the "ownership" of extension key / composer name.

Once you published the extension at one or both registries, please comment on this issue and I'll check again.

**Comment by jpmschuler** [comment]
There is a typo in `composer.json` name: **copyTight**
```"name": "walther/image-copytight",```

**Comment by carsten-walther** [comment]
Thanks for the hint. Now its fixed.

**Comment by DanielSiepmann** [comment]
Thanks for taking action. The documentation request was approved.
You can find the result here: https://docs.typo3.org/p/walther/image-copyright/1.0/en-us/

Looks like you still need to adjust some parts? At least the title on startpage is "Html2PDF".

**Comment by carsten-walther** [comment]
Thanks for the hint. Will be fixed in next commit.
