### ISSUE TITLE
Call to undefined method TYPO3\CMS\Core\Database\Query\QueryBuilder::executeQuery() - TYPO3 10

### ISSUE THREAD

**Issue by medarob** [carsten-walther/image_copyright#10]
TYPO3 10.4.37 and PHP 7.4.33

I added the plugin to a page and added also the TypoScript from the documention and when opening the page I got the following error:

![grafik](https://github.com/carsten-walther/image_copyright/assets/33951787/33ff8241-0ee2-416c-95d7-4e85ec2d8b29)

The method TYPO3\CMS\Core\Database\Query\QueryBuilder::executeQuery() is not available in TYPO3 10.4.
It is available since version 11.5:
https://github.com/TYPO3/typo3/blob/11.5/typo3/sysext/core/Classes/Database/Query/QueryBuilder.php#L293

**Comment by carsten-walther** [comment]
fixed in v 12.4.5
