### ISSUE TITLE
Call to undefined method TYPO3\CMS\Core\Database\Query\Expression\ExpressionBuilder::and() in TYPO3 10.4

### ISSUE THREAD

**Issue by medarob** [carsten-walther/image_copyright#11]
Same problem like with the other issue.

the and() methode is only available since TYPO3 11 and not in TYPO3 10

![grafik](https://github.com/carsten-walther/image_copyright/assets/33951787/0aa2cfed-0e24-4fe0-9f5e-0ab2fab8c6d4)

Maybe there are more missing methodes and it's better to make version 12 compatible with TYPO3 10 and release another version 13 which drops support for TYPO3 10 and adds the changes again - if you have to rewrite the code to make it compatible to TYPO3 10/11/12. Not sure which is the last version that works with TYPO3 10. I'm testing in TYPO3 10 because that's what we use right now but the update to version 11 will happen soon.

**Comment by carsten-walther** [comment]
O.k. ... terrible version hunt with backward compatibility. Now I have dropped typo3 v10 support in the current version.
The last typo3 v10 supported version should be [https://github.com/carsten-walther/image_copyright/releases/tag/1.0.5](https://github.com/carsten-walther/image_copyright/releases/tag/1.0.5).
