### ISSUE TITLE
#1055 Doctrine\DBAL\Exception\DriverException

### ISSUE THREAD

**Issue by PeterProell** [carsten-walther/image_copyright#12]
Installed the extension (12.5.1) with TYPO3 12LTS
included the typoscript in my main template
added the plugin to a page and got this

#1055 Doctrine\DBAL\Exception\DriverException

An exception occurred while executing a query: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'db.sys_file_reference.uid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by carsten-walther** [comment]
You have to reset the sql_mode like e.g.:

```
$GLOBALS['TYPO3_CONF_VARS'] = array_replace_recursive($GLOBALS['TYPO3_CONF_VARS'], [
    'DB' => [
        'Connections' => [
            'Default' => [
                'initCommands' => 'SET SESSION sql_mode = ""'
            ],
        ],
    ],
];
```

in your LocalConfiguration.php or AdditionalConfiguration.php files. Otherwise the extension will not work.
