### ISSUE TITLE
Duplicate link to resource page in default language on multilingual site

### ISSUE THREAD

**Issue by web2date** [carsten-walther/image_copyright#5]
Hi, using your extension on a TYPO3 v11.5.17 multidomain website (DE/EN) the frontend is showing 2 links to the same page instead of 2 links to different languages
![image (3)](https://user-images.githubusercontent.com/8898397/199712125-f03cac44-615f-4571-88ee-1521129ac33a.png)
This seams to be an error in following code as pid is always the default language. But needed is a link to the default and the translated page.
https://github.com/carsten-walther/image_copyright/blob/debfb146356429e78f8dbf6c74e4b38a48344ced/Classes/Resource/FileRepository.php#L240

**Comment by carsten-walther** [comment]
Fixed in version 12.4.2
