### ISSUE TITLE
error in Classes/Resource/FileRepository.php in TYPO3 10 and PHP 7.4.33

### ISSUE THREAD

**Issue by medarob** [carsten-walther/image_copyright#9]
Error in TYPO3 10.4 and PHP 7.4.33:

After installing I get the following error:

  - Installing carsten-walther/image_copyright (12.4.3): Extracting archive
Generating autoload files
Generating class alias map file
Setting up TYPO3 environment and extensions.
**Executing TYPO3 Console command "database:updateschema" failed.**
For details re-run Composer command with increased verbosity (-vvv).
**Executing TYPO3 Console command "extension:setupactive" failed.**

The Stacktrace revealed:
```
  [ ParseError ]                                      
  syntax error, unexpected '|', expecting ';' or '{'  
```

Exception trace:
**#0 ()
   typo3conf/ext/image_copyright/Classes/Resource/FileRepository.php:217**
#1 Composer\Autoload\{closure}()
   vendor/composer/ClassLoader.php:433
#2 Composer\Autoload\ClassLoader->loadClass()
   vendor/typo3/class-alias-loader/src/ClassAliasLoader.php:137
#3 TYPO3\ClassAliasLoader\ClassAliasLoader->loadClass()
   vendor/typo3/class-alias-loader/src/ClassAliasLoader.php:125

![grafik](https://github.com/carsten-walther/image_copyright/assets/33951787/24ff9d03-f076-4ac9-8c78-c583d272c644)

**Comment by carsten-walther** [comment]
fixed in v 12.4.4
